#!/usr/bin/env bash
# powerdown - powerup
#

if [[ $EUID != 0 ]]; then
    echo "[powerdown] must be run as root"
    exit 1
fi

source /usr/lib/powerdown-functions
lock

# bus
for i in /sys/bus/*/devices/*/power/control; do opt "$i" on; done

# usb autosuspend
for i in /sys/bus/usb/devices/*/power/autosuspend; do opt "$i" 600; done
for i in /sys/bus/usb/devices/*/power/control; do opt "$i" on; done

# nmi_watchdog
opt /proc/sys/kernel/nmi_watchdog 1

# cpu
for i in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do opt "$i" performance; done
load_mod msr
run x86_energy_perf_policy normal

# aspm
opt /sys/module/pcie_aspm/parameters/policy default

# kernel write mode
opt /proc/sys/vm/laptop_mode 0
opt /proc/sys/vm/dirty_ratio 30
opt /proc/sys/vm/dirty_background_ratio 10
opt /proc/sys/vm/dirty_expire_centisecs 600
opt /proc/sys/vm/dirty_writeback_centisecs 600

# disk
for i in /sys/class/scsi_host/host*/link_power_management_policy; do opt "$i" medium_power; done
for dev in $(awk '/^\/dev\/sd/ {print $1}' /etc/mtab); do run mount -o remount,relatime "$dev"; done
for dev in $(awk '/^\/dev\/sd/ {print $1}' /etc/mtab); do run blockdev --setra 256 "$dev"; done
for dev in $(awk '/^\/dev\/sd/ {print $1}' /etc/mtab); do run hdparm -B 254 -S 253 "$dev"; done

# sound card
opt /sys/module/snd_hda_intel/parameters/power_save 0
opt /sys/module/snd_hda_intel/parameters/power_save_controller N
opt /sys/module/snd_ac97_codec/parameters/power_save 0

# net
for i in $(iw dev | awk '$1 == "Interface" { print $2 }'); do run iw dev "$i" set power_save off; done
run ethtool -s eth0 wol g

# screen
for i in /sys/class/backlight/*; do opt "$i/brightness" "$(num_scale "$i/max_brightness" 5 )"; done

# webcam
load_mod videodev

# bluetooth
load_mod bluetooth

# open source ATI
opt /sys/kernel/debug/vgaswitcheroo/switch ON
for i in /sys/class/drm/card*/device/power_method; do opt "$i" profile; done
for i in /sys/class/drm/card*/device/power_profile; do opt "$i" default; done
for i in /sys/class/drm/card*/device/power_dpm_state; do opt "$i" balanced; done

# i915
#opt /sys/module/i915/parameters/i915_enable_rc6 0
exit 0
